### ISSUE TITLE
Un seul ue vous manque et tout est dépeuplé (#lamartineStyle)

### ISSUE THREAD

**Issue by parville** [etalab/addok#104]
Chercher via l'api **6 r Alain Chartier 75015 Paris** renvoie une réponse à la rue 
Chercher via l'api **6 r*ue* Alain Chartier 75015 Paris** renvoie une réponse au point de voie 

http://api.adresse.data.gouv.fr/search/?q=6%20r%20Alain%20Chartier%2075015%20Paris&limit=3

http://api.adresse.data.gouv.fr/search/?q=6%20rue%20Alain%20Chartier%2075015%20Paris&limit=3

On eut pu imaginer qu'il fut capable de proposer le point de voie dans les deux cas ? 

Merci !!!

**Comment by parville** [comment]
Il y a bien la variante : L'r qui me pompe ! 
car 

Chercher via l'api **6 ~~rue~~ Alain Chartier 75015 Paris** renvoie une réponse au point de voie

**Comment by yohanboniface** [comment]
Fixed in https://github.com/etalab/addok/commit/dfdde90106abaf5adf4ead5225c1ca47842cf309
See also #99
