### ISSUE TITLE
ADDOK - Cas de double réponse inattendue : housenumber + street

### ISSUE THREAD

**Issue by parville** [etalab/addok#111]
A la question suivante 

http://api.adresse.data.gouv.fr/search/?q=11 RUE BOUTROLLE ESTAIMBUC&citycode=76451&limit=5

* je dirai qu'on cherche clairement un numéro dans une rue de la commune de code INSEE 76451*

on obtient *curieusement* deux réponses :

type |  name | citycode
---- | ----- | -----
housenumber | **11** Rue Jacques Boutrolle d'Estaimbuc | 76451
street | Rue Jacques Boutrolle d'Estaimbuc | 76451

La seconde réponse est superflue et est dans la première !

Est-ce le fait que cette voie soit définie deux fois dans la BAN qui vient perturber le ciblage de la réponse fournie par ADDOK ? La voie existe comme
* Rue Jacques Boutrolle d'Estaimbuc *alias* Rue Jacques Boutrolle
* Rue Jacques Boutrolle

HP

Détail  : 

> {"type": "Feature", "properties": {"type": "housenumber", "name": "11 Rue Jacques Boutrolle d'Estaimbuc", "city": "Mont-Saint-Aignan", "citycode": "76451", "postcode": "76130", "score": 0.5049312805474094, "housenumber": "11", "context": "76, Seine-Maritime, Haute-Normandie", "id": "ADRNIVX_0000000272805234", "label": "11 Rue Jacques Boutrolle d'Estaimbuc 76130 Mont-Saint-Aignan"}, "geometry": {"type": "Point", "coordinates": [1.074518, 49.461082]}}, 

> {"type": "Feature", "properties": {"type": "street", "city": "Mont-Saint-Aignan", "citycode": "76451", "postcode": "76130", "score": 0.4711057673509286, "name": "Rue Jacques Boutrolle d'Estaimbuc", "context": "76, Seine-Maritime, Haute-Normandie", "id": "76451_XXXX_cae029", "label": "Rue Jacques Boutrolle d'Estaimbuc 76130 Mont-Saint-Aignan"}, "geometry": {"type": "Point", "coordinates": [1.078103, 49.460556]}}

**Comment by yohanboniface** [comment]
> Est-ce le fait que cette voie soit définie deux fois dans la BAN qui vient perturber le ciblage de la 
> réponse fournie par ADDOK ?

Oui, deux identifiants == deux objets distincts pour addok. A corriger côté data ;)
