### ISSUE TITLE
Plugin: missing acces to post()' fieldnames from subclass of BaseCSV

### ISSUE THREAD

**Issue by frodrigo** [etalab/addok#116]

**Comment by frodrigo** [comment]
The commit change nothing to the problem. Since `self.rows` is computed and used in the same `post()` method without the possibility to use it from subclass before the row are processed.

In my case I want do extra sanity check of parameters before looping on rows.

**Comment by yohanboniface** [comment]
Can you check with last commit?

**Comment by frodrigo** [comment]
Thank. It's do the job for me.
