### ISSUE TITLE
Les champs HOUSENUMBERS_PAYLOAD_FIELDS ne s'affichent pas

### ISSUE THREAD

**Issue by Apside-bdx-BBO** [etalab/addok#135]
Mis à part id, les clés définis dans 'HOUSENUMBERS_PAYLOAD_FIELDS' ne semblent pas remonter dans la réponse. 
Ils sont bien enregistrés dans la base Redis.
Il semble que les valeurs restent en _cache mais ne sont pas restituées lors de la formation de la réponse (core.py).

Missing "export payload in result" (#134)

**Comment by yohanboniface** [comment]
Erf, sorry, should be fixed now :)
