### ISSUE TITLE
Utiliser l'api depuis un serveur Postgresql 

### ISSUE THREAD

**Issue by diouck** [etalab/addok#141]
Je viens d'installer le serveur BAN/BANO en local et ça marche très bien.
Je voudrai savoir comment intégrer les données et faire directement les requêtes depuis ma base de données Postgresql.
Merci de votre compréhension

**Comment by yohanboniface** [comment]
http://addok.readthedocs.org/en/latest/import/#import-from-nominatim si c'est une base nominatim, sinon faut coder un wrapper pour mettre les données psql au bon format.
