### ISSUE TITLE
No Data fail without error notification

### ISSUE THREAD

**Issue by Ecologeek** [etalab/addok#17]
If there is a line with no data, nothing happend, and no error is raised.
test with :
> NOM;NUM;RUE;CODE POSTAL;VILLE
> ;;;;

if there is a something in a column, it's working, unless you don't select this column:
> NOM;NUM;RUE;CODE POSTAL;VILLE
> XXX;;;;
- select all columns : it work
- don't select column NOM: it didn't work

**Comment by yohanboniface** [comment]
Thanks for the report, it should be fixed now :)
