### ISSUE TITLE
Can't find 'Y' (80190)

### ISSUE THREAD

**Issue by vdct** [etalab/addok#26]
Tested on http://adresse.data.gouv.fr/map/ : 
'Y' in the input search gives 0 suggestion and pressing 'Enter' does not trigger anything. 
Expected result : http://www.openstreetmap.org/relation/909020

**Comment by yohanboniface** [comment]
Yep, good point. That's an issue of the front side, though, as the javascript triggers the ajax call only with three letters or more (So problem occurs also for Oô, Py, By, etc.). This needs to be fixed indeed.
Note that searching for "Y" in the console gives the expected result.

**Comment by yohanboniface** [comment]
Now you can :)

**Comment by vdct** [comment]
\o/
