### ISSUE TITLE
BANO data link in import instructions doesn't work anymore

### ISSUE THREAD

**Issue by richterb** [etalab/addok#27]
Regarding importing data, the README links to https://github.com/etalab/addok/blob/master/bano.openstreetmap.fr/data/full.sjson.gz but it seems there is nothing here anymore. I'd have fixed myself but I can't find where it's gone :)

**Comment by yohanboniface** [comment]
Thanks for the report :)

**Comment by yohanboniface** [comment]
(Note that I'm in a the way of refactoring the import process to import also OSM POIs data, so I don't know what you plan to use addok for, but in case you also want OSM data ping me so I finish and push my work. :) )

**Comment by richterb** [comment]
No rush, we're more interested by BANO data for now :) (pure geocoding of data in a backend, so it's rather about addresses)
