### ISSUE TITLE
b/bis t/ter

### ISSUE THREAD

**Issue by cquest** [etalab/addok#30]
11b rue de Clamart 92100 Boulogne-Billancourt
ne trouve pas le 11bis (qui existe)

un post-traitement pour les b/t/q/c/s serait utile pour les retrouver quelle que soit l'adresse en entrée.

**Comment by yohanboniface** [comment]
humm, peut-être qu'il suffit de les gérer dans les synonymes, faut que je checke :)

**Comment by yohanboniface** [comment]
Si on ajoute "b => bis" dans les synonymes, on aura quelques effets de bord sur des trucs genre "Résidence B Maisons-Alfort", "Parking B Cachan", "Espace B Paris". Mais on peut peut-être dire qu'on s'en fout.

**Comment by cquest** [comment]
Je pensais à un truc moins radical que les synonymes globaux.
Possible de pré-processer ça... mais il faudrait une façon de fournir ces tokens supplémentaires à indexer.

**Comment by cquest** [comment]
J'ai testé en mettant les variante du numéros dans le json d'entrée, exemple:
140B -> 140B,140 B,140bis,140 bis

La recherche fonctionne, mais l'adresse retournée contient donc toutes les variantes.

**Comment by yohanboniface** [comment]
Je vois. On peut ajouter une clé "alias" dans chaque housenumber éventuellement, et l'indexer?

**Comment by cquest** [comment]
Ca serait le plus simple, sauf si tu gère ces cas particuliers automatiquement dans addok.
L'alternative que j'ai pour l'instant c'est de créer 4 adresses pour les 4 variantes.
Autre solution, un champ "ext" en plus où l'on met "bis" et tu teste numéro+ext, numéro+" "+ext, numéro+left(ext,1) numéro+" "+left(ext,1)...

**Comment by yohanboniface** [comment]
Lequel de `quater` et `quinquies` devient `q`? Et du coup, que devient l'autre? :)

**Comment by yohanboniface** [comment]
```
> 64b Rue de Metz Armentières
64B Rue de Metz 59280 Armentières (59017_1510_740b8f | 0.7565999999999999)
22.8 ms / 1 results
--------------------------------------------------------------------------------
> 64 BIS Rue de Metz Armentières
64B Rue de Metz 59280 Armentières (59017_1510_740b8f | 0.6076442260442261)
14.0 ms / 1 results
--------------------------------------------------------------------------------
> 64 Rue de Metz Armentières
64 Rue de Metz 59280 Armentières (59017_1510_740b8f | 0.7511014662756598)
11.6 ms / 1 results
--------------------------------------------------------------------------------
```

(Je pars sur `quater` => `q`, `quinquies` => `c`.)

**Comment by cquest** [comment]
quater -> q
quinquies -> c (comme cinq, voir http://r.duckduckgo.com/l/?kh=-1&uddg=http%3A%2F%2Fwww.dsi.cnrs.fr%2Fconduite-projet%2Fphasedeveloppement%2Ftechnique%2Fetude-detaillee%2Fmodele-de-donnees%2Fregles-enregistrement-adresses-postales.doc)
