### ISSUE TITLE
Lien cassé README

### ISSUE THREAD

**Issue by ksahin** [etalab/addok#31]
Le lien vers nominatim dans le README est cassé !

D'ailleurs si vous pouviez m'expliquer : Nomitatim étant l'API d'openstreetmap, et bano étant composé des données d'OSM + cadastre (+ autre sources ? ) a quoi ça sert d'importer la base nominatim ? 
Car si j'ai bien compris BANO est sensé être plus complet qu'osm . 

Merci

**Comment by yohanboniface** [comment]
BANO ne concerne que les adresses, Nominatim contient tout le reste ;)

**Comment by ksahin** [comment]
Ah oui je vois, merci !
