### ISSUE TITLE
paradoxe sur le score

### ISSUE THREAD

**Issue by parville** [etalab/addok#32]
Bonjour,

*si je cherche*
api.adresse.data.gouv.fr/search/?q=**30%20bis%20**rue%20brisout%20de%20barneville%2076000%20Rouen&limit=1 

*j'obtiens*
> "label": "**30bis** Rue Brisout de Barneville 76000 Rouen",
>"score": **0.896**..., 
>"query": "30 bis rue brisout de barneville 76000 Rouen"

*si je cherche avec la forme suggérée par la réponse* 
api.adresse.data.gouv.fr/search/?q=**30bis**%20rue%20brisout%20de%20barneville%2076000%20Rouen&limit=1

*j'obtiens paradoxalement un score plus faible* 
>  "label": "**30bis** Rue Brisout de Barneville 76000 Rouen", 
>  "score": **0.867**...,, 
> "query": "30bis rue brisout de barneville 76000 Rouen", 

*Plus étonnant encore, si je cherche*  
api.adresse.data.gouv.fr/search/?q=**30bis**%20rue%20brisout%20de%20barneville%20**76100**%20Rouen&limit=1 
*le score remonte alors que selon les termes de la réponse je m'en suis éloigné en demandant le ZIP 76100 dans la question.* 
> "label": "30bis Rue Brisout de Barneville **76000** Rouen" 
> "score": **0.875**

*Partagez-vous la suite de mon étonnement si je demande* 
api.adresse.data.gouv.fr/search/?q=**30%20bis**%20rue%20brisout%20de%20barneville%20**76100**%20Rouen&limit=1
*et que je constate*
>"label": "30bis Rue Brisout de Barneville 76000 Rouen"
>"score": **0.820**

**Synthèse**

Rang  | Numéro | ZIP | Score | Label de la réponse 
--------|------------|------|--------|----------------------------
1 | 30 bis | 76000 |  0.896 | "30bis Rue Brisout de Barneville 76000 Rouen"
2 | 30bis | 76100 | 0.875 | 30bis Rue Brisout de Barneville 76000 Rouen"
3 | 30bis | 76000 | 0.867 | "30bis Rue Brisout de Barneville 76000 Rouen"
4 | 30 bis | 76100 | 0.820 | "30bis Rue Brisout de Barneville 76000 Rouen"

Nota : 

Dans tous les cas, le ZIP de la réponse est faux. 

Questions

1. Pourquoi la question la plus proche du label de réponse n'a-t-elle pas le score le plus élevé ?
2. Pourquoi demander 30bis / 76100 est mieux noté que 30bis/76000 ?
3. Pourquoi un tel écart entre 30 bis / 76000 et 30 bis / 76100 ?
4. Pourquoi le score plafonne-t-il à 0.90 ? Même avec un lon/lat on gagne peu très peu.

Hypothèse : 

dans le jeu de données initial le ZIP associé à la voie est erroné: 
Dans le json de BANO on trouve 76000 semble-t-il.  *Pas trouvé ce qui explique le score relatif du 76100 !*

Bien cordialement, HP

**Comment by cquest** [comment]
Le ZIP dans les données est bien erroné... une boundary=postal_code peut être ajoutée dans OSM pour définir la zone couverte par 76100, mais ceci dépasse le cadre de addok...

30 bis/76100 est logiquement plus éloigné de l'adresse en base, normal donc que la note baisse (cas 4) mais pas normal pour le cas 2.

30 bis/76000 et 30bis/76000 devraient rendre une valeur identique, l'espace ne devrait pas jouer.

Sur la note qui plafonne, c'est lié à l'importance intrinsèque de cette rue dans cette commune et parce que la requête est fait en mode "auto-complétion" par défaut. Rajoute autocomplete=false à la requête pour une note sans critère d'importance (manque dans la doc en ligne).

**Comment by yohanboniface** [comment]
autocomplete=0 :)

Pour le "30 bis"/"30bis", pas mieux, ça ressemble à un bug, je vais regarder.

**Comment by cquest** [comment]
Doc mise à jour sur le site: https://github.com/etalab/adresse.data.gouv.fr/commit/9033921407a0133cbf4aae47b651d7e02ab86f45

**Comment by yohanboniface** [comment]
:)

**Comment by yohanboniface** [comment]
Voilà, ça devrait être corrigé. :)

Ref: https://github.com/etalab/addok/commit/08d122340d16a4a41b20da285c7eb66e6dbe810f
