### ISSUE TITLE
Include attribution and license in results

### ISSUE THREAD

**Issue by richterb** [etalab/addok#35]
Since addok is datasource-agnostic, it may be a good idea in my opinion to include attribution and possibly the license into the result JSON. I'm thinking that if you find an addok instance in the wild, or even parallel instances of addok with different data for various needs (FANTOIR...), it ensures you know the origin and how to handle it. Maybe it could even be included in the GeocodeJSON spec.

Maybe something as trivial as two optional keys in the config file is enough; then we'd add them at the root of the JSON result.

**Comment by yohanboniface** [comment]
Good point :)

I'm just wondering if we'll not find the case where attribution and licence are different *per* result, for example mixing Open Licence and ODBL data in the same instance :s

**Comment by richterb** [comment]
Yeah, that will probably happen one day :)
We could add it at the single result level; and when importing BANO, Nominatim, or other sources, it could a single value hardcoded in the specific importer, and later a command-line option if we have a generic importer; the license and attribution would be added to each imported address.
I'm a bit worried about the impact on the size of the index though?

As a first step we also could just add the two keys in the configuration, and add them to each result on the fly; the day we need to be smarter, at least the result format won't change. It probably makes sense.

**Comment by yohanboniface** [comment]
Yep, let do something like this:
- keep the attribution on the root of the results GeoJSON
- (optionally) add the source of the data of each documents
- and make that the attribution can be a dict like `source1: attribution, source2: attribution` (so we only add the source key to the document in the index)
