### ISSUE TITLE
Ancien nom de ville / nom de quartier

### ISSUE THREAD

**Issue by parville** [etalab/addok#36]
La recherche " *neuville les dieppe* 15  route de bonne nouvelle 76370 Dieppe " ne fournit **aucun résultat**

La recherche "15  route de bonne nouvelle 76370 Dieppe " fournit le **15  route de bonne nouvelle 76370 Dieppe**

*neuville les dieppe* est d'une certaine façon un synonyme du 76370 puisqu'il s'agit d'une commune fusionnée de longue date avec Dieppe qui devenue quartier de Dieppe a conservé son code postal.

La formulation telle que vient d'une source tierce (annuaire opérateur). Considérez-vous qu'il faudrait retraiter en amont d'addok la donnée source ? ou bien qu'addok ne devrait pas faire chou blanc.

Merci !

**Comment by parville** [comment]
Variante de recherche

" *resid goelands* **28  impasse des petrels 76460 Saint-valery-en-caux** " ne retourne rien

mais 

"**28  impasse des petrels 76460 Saint-valery-en-caux**" est ok

Faut-il en amont d'addok arriver à établir que *resid goelands* est un segment d'adresse non addok-signifiant  ? 

Merci

**Comment by yohanboniface** [comment]
> " resid goelands 28 impasse des petrels 76460 Saint-valery-en-caux " ne retourne rien

Humm: http://api.adresse.data.gouv.fr/search/?q=resid%20goelands%2028%20impasse%20des%20petrels%2076460%20Saint-valery-en-caux&limit=1 retourne bien le résultat attendu.

**Comment by parville** [comment]
Tournée générale pour l'équipage de la part du capitaine ! :no_mouth:

**Comment by parville** [comment]
Pourr le cas de St Valéry en Caux, j'ai trouvé la cause de la non réponse ! 

2 espaces consécutifs dans la chaine de recherche après le numéro dans la voie ! Le fait de mettre 2 espaces consécutifs ailleurs ne provoque pas le gag !

Nota : On peut reproduire le problème avec l'exemple de Neuville Les Dieppe :green_heart:

**Comment by yohanboniface** [comment]
Bien vu, je vais corriger ça :)

**Comment by yohanboniface** [comment]
Note: je te réponds depuis Pourville-sur-Mer, c'est dire si je me sens concerné ;)

(Pourville-sur-Mer, qui d'ailleurs n'est pas une commune à proprement parler…)

**Comment by parville** [comment]
Tu vas pouvoir faire un relevé de la rue Mozart à Dieppe alors ! Totalement manquante dans OSM 
Tu es bien servi pour la météo :star::star::star: !

**Comment by yohanboniface** [comment]
Voilà, c'est corrigé pour les multiples espaces, merci pour le rapport de bug! :)
