### ISSUE TITLE
Voie connue dans OSM non retrouvée dans addok

### ISSUE THREAD

**Issue by parville** [etalab/addok#37]
Bonjour,

**périphérique henri wallon 76800 Saint-etienne-du-rouvray** est une voie connue dans OSM ( http://www.openstreetmap.org/#map=18/49.39412/1.07099 )

On note que cette voie ne comporte pas de numéro de voies. 

Dans addok, la recherche **périphérique henri wallon 76800 Saint-etienne-du-rouvray** ne retourne rien. Est-ce un soucis d'alimentation d'addok ? 

La question de pouvoir interroger **tour tourmalet périphérique henri wallon 76800 Saint-etienne-du-rouvray** semble se poser, faute de numéro dans la voie. 

Est-il techniquement possible de faire d'un bâtiment un pseudo point de voie ? 

Qu'en pensez-vous ?
Merci

HP

**Comment by yohanboniface** [comment]
@cquest @vdct j'ai pas l'impression de l'avoir dans les données, une idée?

> La question de pouvoir interroger tour tourmalet périphérique henri wallon 76800 Saint-etienne-
> du-rouvray semble se poser, faute de numéro dans la voie.
> Est-il techniquement possible de faire d'un bâtiment un pseudo point de voie ?

Je dirais qu'il suffit d'intégrer les bâtiments ayant un nom comme des POIs.

**Comment by cquest** [comment]
Cette voie n'a pas d'adresse connue, donc ne sort pas de BANO actuellement. C'est une limitation actuelle de BANO, mais on pourrait effectivement sortir un peu plus de choses.

A voir sur les données BAN dans 2 semaines...

**Comment by cquest** [comment]
J'ai modifié le script d'export json de BANO pour sortir les voies rapprochées (donc on a une géométrie pour la voie) mais sans adresse.

https://github.com/osm-fr/bano/blob/master/out/banout-json.sh#L80

**Comment by cquest** [comment]
Données mises à jour, on retrouve bien désormais :
- Périphérique Henri Wallon : http://api.adresse.data.gouv.fr/search/?q=peripherique%20henri%20wallon
- Tour Tourmalet : http://api.adresse.data.gouv.fr/search/?q=tour%20tourmalet
