### ISSUE TITLE
Absence de réponse, réponse niveau street  attendue

### ISSUE THREAD

**Issue by parville** [etalab/addok#38]
La question " **2719 route de neufchatel  76230 Bois-guillaume** " retourne une réponse housenumber
La question " **2909 route de neufchatel  76230 Bois-guillaume** " ne retourne rien

A défaut de connaitre le *2909* addok ne devrait-il pas retourner la rue ? 

Merci 

HP

**Comment by vdct** [comment]
Pour du géocodage, oui, on doit retourner un point à la rue à défaut d'un point au numéro. C'est une des raisons du contenu BANO "voie".
En revanche il est impératif de retourner un code de réponse qui fait comprendre qu'on n'a pas pu considérer le n° demandé, qu'il n'y ait pas de méprise sur l'interprétation (géographique) du point retourné.

**Comment by parville** [comment]
Vincent, le champ **type** permet cela et retourne *habituellement* :confused: **Street** pour voie au lieu de **HouseNumber**  :exclamation:

**Comment by yohanboniface** [comment]
> Vincent, le champ type permet cela et retourne habituellement :confused: Street pour voie au lieu de 
> HouseNumber 

Ça a été corrigé, ça.

> La question " 2719 route de neufchatel 76230 Bois-guillaume " retourne une réponse housenumber
> La question " 2909 route de neufchatel 76230 Bois-guillaume " ne retourne rien

En base, le code postal est 76420. Numéro inconnu et "mauvais" code postal, c'en est trop pour addok. Je vais voir si je peux bouger un peu le curseur mais sans garantie.

**Comment by parville** [comment]
Yohan,

Il y a un soucis aussi sur les données car 76230 est le bon ZIP et 76420 chargé dans addok n'est pas correct.

76230 désigne bien Bois-Guillaume
76420 désigne Bihorel


Par contre on pourrait imaginer que 76420 soit un synonyme de 76230 étant donné que si on regarde sur http://www.laposte.fr/particulier/outils/trouver-un-code-postal on a :

![zip-76230-20150307](https://cloud.githubusercontent.com/assets/7741025/6541589/0948cac6-c4db-11e4-940a-dccaf17d2f0f.png)

et 

![zip-76420-20150307](https://cloud.githubusercontent.com/assets/7741025/6541590/1729f976-c4db-11e4-9de6-1692fb89b70d.png)

ce qui tend à démontrer que le temps s'est arrêté au 31/12/2013 à La Poste , avant la défusion de Bois-Guillaume et Bihorel .

PS : Je fais du coup aussi un signalement sur /adresse.data.gouv.fr.

**Comment by cquest** [comment]
C'est corrigé pour les futurs exports...

https://github.com/osm-fr/bano/commit/7dac65ae4b2b09a043911c7672fa5530167ec028
