### ISSUE TITLE
Caramba !!

### ISSUE THREAD

**Issue by parville** [etalab/addok#41]
Le géocodage du **15 route de Saint Romain 76430 La Cerlangue** propose 

1. Route de la Cerlangue 76430 Saint-Romain-de-Colbosc :bomb: 
2. **Route de Saint-Romain 76430 La Cerlangue**

 :cold_sweat:

http://api.adresse.data.gouv.fr/search
/?q=15%20route%20de%20saint%20romain%2076430%20La%20Cerlangue&limit=3

**Comment by yohanboniface** [comment]
Je vois ça:

```
> 15 route de Saint Romain 76430 La Cerlangue
Route de Saint-Romain 76430 La Cerlangue (761690004X | 0.8475103896103895)
Route de la Cerlangue 76430 Saint-Romain-de-Colbosc (766470115P | 0.6904445969125214)
```

**Comment by parville** [comment]
Bon bah ce matin le résultat est celui attendu.... Hum !
