### ISSUE TITLE
Score > 1 

### ISSUE THREAD

**Issue by parville** [etalab/addok#42]
Dans la présentation addok il est indiqué que le score est entre 0 et 1.
Si on cherche le **41 rue d Iena 76600 Le Havre**, le score est 1.3096363636363635 !
Sans doute l'effet du Grand Paris :laughing:  ?

http://api.adresse.data.gouv.fr/search/?q=41%20%20rue%20d%20iena%2076600%20Le%20Havre

PS : autant de décimales dans le score ne parait pas utile.

**Comment by yohanboniface** [comment]
Merci, effet de bord d'un changement récent, qui manquait de test unitaire. C'est corrigé, et le test unitaire ajouté :)
