### ISSUE TITLE
Gestion des accents dans le géocodeur CSV

### ISSUE THREAD

**Issue by sylvain-m** [etalab/addok#43]
Je viens d'essayer le géocodeur CSV avec quelques données test : celui-ci a très bien fonctionné, sauf lorsque les adresses contenaient des accents.
Par exemple, les "è" sont devenus des "ï¿½", et le géocodage n'a donc donné aucun résultat.
J'ai essayé depuis un CSV, un TXT, même problème.
Certainement un problème de gestion de l'encodage.

Bravo pour ce super outil en perspective !

Sylvain M.

**Comment by yohanboniface** [comment]
Essaie d'encoder ton fichier en UTF-8 avant et dis-moi.
Faut qu'on voie comment être un peu plus malin sur l'encodage, mais pour le coup avec du CSV c'est pas évident d'être fin…

**Comment by sylvain-m** [comment]
En UTF8, le "è" devient "Ã¨" (et plus "ï¿½"), et le géocodage ne fonctionne pas non plus...

**Comment by yohanboniface** [comment]
Oui, ça colle. Pour l'instant on ne supporte que l'UTF-8.

**Comment by sylvain-m** [comment]
OK.
Je sais pas si ça peut être utile, mais comme il y a beaucoup d'utilisateurs de Microsoft Excel (je sais, c'est mal), ça serait peut-être pratique, dans le fichier en sortie, d'utiliser cette ruse pour qu'excel charge directement en UTF-8 : http://www.ygi.ch/forcer-ouverture-fichier-csv-utf-8-excel/
(ajouter le caractère “BOM UTF-8″, non imprimable, au début du fichier)
Sinon, il serait aussi utile de préciser dans l'application que les données en entrée doivent être dans cet encodage.
Merci à vous.

Sylvain M.

**Comment by yohanboniface** [comment]
@sylvain-m je viens d'ajouter le BOM, à l'occasion tu peux retester depuis Excel voir s'il couine? Merci :)

**Comment by sylvain-m** [comment]
Testé ce jour, mais malheureusement, Excel (Office 2007 Pro me concernant) ne comprends toujours pas que c'est de l'UTF-8...
Mais bon, Open Office s'en sort très bien, donc pas de souci insurmontable.

**Comment by yohanboniface** [comment]
On peut maintenant préciser l'encodage: http://adresse.data.gouv.fr/csv/ :)
