### ISSUE TITLE
Opportunité d'une recherche avec critère INSEE

### ISSUE THREAD

**Issue by parville** [etalab/addok#51]
Bonjour j'ai noté la forme 
> http://api-adresse.data.gouv.fr/search/?q=8 bd du port&postcode=44380  

Peut-on imaginer d'avoir une forme ?
> http://api-adresse.data.gouv.fr/search/?q=12 rue jeanne d'arc&codeinsee=76540 

Ca serait _super_ !

**Comment by yohanboniface** [comment]
C'est en prod, le paramètre est `citycode`.
Par exemple: http://api-adresse.data.gouv.fr/search/?q=12%20rue%20jeanne%20d%27arc&citycode=76540 :)
