### ISSUE TITLE
La Cosnière - Saint-Mars-d'Egrenne

### ISSUE THREAD

**Issue by sylvain-m** [etalab/addok#56]
En espérant que ce soit bien le lieu pour signaler un retour d'adresse infructueux.
La recherche en objet retourne 3 résultats : 
- La Haute Conière
- La Basse Cornière
- La Haute Cornière

Ce qui est étrange, c'est que le lieudit "La Cosnière" est pourtant bien présent sur le fond de plan IGN.
Une idée de la cause du problème ? (au dela des doublons / fautes d'orthographes).

Bon courage !

A+

Sylvain M.

**Comment by cquest** [comment]
J'ai vérifié les data et il n'y a pas d'adresse avec "Cosnière" dans cette commune.

Mais on voit des adresses proches sur (en gris = source BAN) :
http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#17/48.56003/-0.74179

Ces adresses sont indiquée au lieu-dit "La Haute Conière", il s'agirait donc d'une erreur de libellé du lieu-dit dans les données adresses, mais pas dans les données topo/carto utilisées pour le fond "Plan IGN".

addok par contre se comporte bien en trouvant ces adresses...

**Comment by sylvain-m** [comment]
Merci pour l'enquête.
Pour information, localement, c'est "La Cosnière" qui est utilisé, cf. cette copie d'écran Street View : 
https://www.google.fr/maps/@48.560286,-0.738901,3a,20.4y,343.55h,76.85t/data=!3m4!1e1!3m2!1syULVUR-5QtNAdOOfbbdA7g!2e0
A+

Sylvain M.
