### ISSUE TITLE
Batch reverse geocoder

### ISSUE THREAD

**Issue by CharlesNepote** [etalab/addok#58]
Reverse geocoding is only possible one item at a time.
Could it be possible to do reverse geocoding from a CSV file?

Suggestions:
* /csv/ in the API should be renamed /geocodeFromCSV/
* create a /reverseFromCSV/ in the API
* add possibility to do reverse geocoding with command line such as:
  * $ addok reverseFromCSV  path/to/file.csv

Examples of use cases:
* find all city names of POIs (example: POIs exported from OSM)
* provide a delimitation of a polygon with real addresses

Here is a very concrete need for me (last command is a dream):

    $ wget http://download.geofabrik.de/europe/france/provence-alpes-cote-d-azur-latest.osm.pbf # télécharge le fichier OSM de la Région PACA
    $ ./osmconvert32 provence-alpes-cote-d-azur-latest.osm.pbf -o=provence-alpes-cote-d-azur-latest.o5m # conversion du dit fichier dans un format lisible pour osmfilter
    $ ./osmfilter32 provence-alpes-cote-d-azur-latest.o5m --keep="amenity=pharmacy" > PACA-pharmacies.o5m # filtrage proprement dit pour ne retenir que les pharmacies
    $ ./osmconvert32 PACA-pharmacies.o5m --all-to-nodes --csv="@id @lon @lat amenity shop name" --csv-headline > PACA-pharmacies.csv # conversion du fichier filtré en CSV
    $ addok reverseFromCSV  PACA-pharmacies.csv > PACA-pharmacies-with-city-names.csv

Thanks!

**Comment by yohanboniface** [comment]
Doc added in http://adresse.data.gouv.fr/api/ too.
