### ISSUE TITLE
nombres dans les libellés de voies: 8 rue mil huit cent quatorze toulouse

### ISSUE THREAD

**Issue by cquest** [etalab/addok#59]
8 rue mil huit cent quatorze toulouse
renvoie au 14 Rue Milhes 31300 Toulouse

Avec 8 rue 1814 Toulouse, on obtient "Rue 1814 31500 Toulouse", mais par le numéro alors qu'il est présent dans les données BAN

**Comment by cquest** [comment]
Problème identique sur: 43 Rue des Trente-six Ponts TOULOUSE
retourne: 6 Rue des Troènes 31200 Toulouse

43 Rue des 36 Ponts TOULOUSE
retourne: Rue des 36 Ponts Toulouse
ceci vient de 2 adresses ne comportant pas de code postal...

43 Rue des 36 Ponts 31400 TOULOUSE
retourne bien la bonne adresse.

**Comment by yohanboniface** [comment]
Bizarre, y a deux documents pour la même rue on dirait (deux ids différents):
```
> 43 Rue des 36 Ponts TOULOUSE
Rue des 36 Ponts Toulouse (31555_XXXX_ba4c3b | 0.8255626262626261)
43 Rue des 36 Ponts 31400 Toulouse (31555_XXXX_721b90 | 0.780701652892562)
```
