### ISSUE TITLE
76 bis rue pasteur 01

### ISSUE THREAD

**Issue by julien2512** [etalab/addok#64]
L'adresse "76 rue pasteur 01" permet bien de trouver en premier résultat une adresse du département 01 (et même celle cherchée en second résultat), mais "76 bis rue pasteur 01" nécessite la saisie complète du code postal pour être trouvée (soit "76 bis rue pasteur 01500").

**Comment by julien2512** [comment]
Je n'ai compris qu'après ! Apparemment, il faut saisir "76bis" tout collé pour que l'adresse soit trouvée directement.
Du coup, je ne comprends pas pourquoi "76 bis" est trouvé lorsque le code postal complet est saisi ...

**Comment by yohanboniface** [comment]
```
> EXPLAIN 76 bis rue pasteur 01
[0.705] Taken tokens [<Token pasteur>, <Token 76bi>]
[0.733] Common tokens [<Token 01>, <Token ru>]
[0.742] Not found tokens []
[0.753] ** STEP_ONLY_COMMONS **
[0.763] ** STEP_NO_MEANINGFUL_BUT_COMMON_TRY_AUTOCOMPLETE **
[0.772] ** STEP_BUCKET_WITH_MEANINGFUL **
[0.787] New bucket with keys ['w|pasteur', 'w|76bi'] and limit 10
[1.863] 10 ids in bucket so far
[1.883] New bucket with keys ['w|pasteur', 'w|76bi'] and limit 0
[2.274] 12 ids in bucket so far
[2.288] ** STEP_REDUCE_WITH_OTHER_COMMONS **
[2.299] ** STEP_ENSURE_GEOHASH_RESULTS_ARE_INCLUDED_IF_CENTER_IS_GIVEN **
[2.308] ** STEP_AUTOCOMPLETE **
[2.320] Autocompleting 01
[2.393] Found tokens to autocomplete set()
[2.407] ** STEP_CHECK_BUCKET_FULL **
[2.418] Computing results
[7.395] Done computing results
76BIS Rue Pasteur 02000 Laon (02408_2020_449390 | str_distance: 0.5667/1.0, importance: 0.0351/0.1)
76BIS Rue Pasteur 62153 Souchez (62801_0620_9512df | str_distance: 0.4706/1.0, importance: 0.0038/0.1)
76BIS Rue Pasteur 59750 Feignies (59225_0410_a51662 | str_distance: 0.4571/1.0, importance: 0.0058/0.1)
76BIS Rue Pasteur 95100 Argenteuil (95018_4060_c687b4 | str_distance: 0.4324/1.0, importance: 0.0298/0.1)
76BIS Rue Pasteur 01500 Saint-Denis-en-Bugey (01345_0135_41db70 | str_distance: 0.4318/1.0, importance: 0.0035/0.1)
76BIS Rue Pasteur 02390 Origny-Sainte-Benoite (02575_0105_938436 | str_distance: 0.3913/1.0, importance: 0.0032/0.1)
76BIS Avenue Pasteur 93100 Montreuil (93048_7160_017471 | str_distance: 0.3415/1.0, importance: 0.023/0.1)
76BIS Rue Pasteur 41310 Saint-Amand-Longpré (41199_0074_75ff03 | str_distance: 0.3478/1.0, importance: 0.016/0.1)
76BIS Avenue Pasteur 93260 Les Lilas (93045_7130_0087d4 | str_distance: 0.3415/1.0, importance: 0.0199/0.1)
76BIS Avenue Pasteur 66130 Ille-sur-Têt (66088_0308_9174b5 | str_distance: 0.3182/1.0, importance: 0.0058/0.1)
7.7 ms / 10 results
--------------------------------------------------------------------------------
> EXPLAIN 76bis rue pasteur 01
[0.682] Taken tokens [<Token pasteur>, <Token 76bi>]
[0.709] Common tokens [<Token 01>, <Token ru>]
[0.718] Not found tokens []
[0.743] ** STEP_ONLY_COMMONS **
[0.755] ** STEP_NO_MEANINGFUL_BUT_COMMON_TRY_AUTOCOMPLETE **
[0.764] ** STEP_BUCKET_WITH_MEANINGFUL **
[0.778] New bucket with keys ['w|pasteur', 'w|76bi'] and limit 10
[4.313] 10 ids in bucket so far
[4.350] New bucket with keys ['w|pasteur', 'w|76bi'] and limit 0
[4.986] 12 ids in bucket so far
[5.007] ** STEP_REDUCE_WITH_OTHER_COMMONS **
[5.021] ** STEP_ENSURE_GEOHASH_RESULTS_ARE_INCLUDED_IF_CENTER_IS_GIVEN **
[5.030] ** STEP_AUTOCOMPLETE **
[5.042] Autocompleting 01
[5.122] Found tokens to autocomplete set()
[5.137] ** STEP_CHECK_BUCKET_FULL **
[5.149] Computing results
[10.00] Done computing results
76BIS Rue Pasteur 01500 Saint-Denis-en-Bugey (01345_0135_41db70 | str_distance: 0.9/1.0, importance: 0.0035/0.1)
76BIS Rue Pasteur 02000 Laon (02408_2020_449390 | str_distance: 0.6429/1.0, importance: 0.0351/0.1)
76BIS Rue Pasteur 62153 Souchez (62801_0620_9512df | str_distance: 0.5312/1.0, importance: 0.0038/0.1)
76BIS Rue Pasteur 59750 Feignies (59225_0410_a51662 | str_distance: 0.5152/1.0, importance: 0.0058/0.1)
76BIS Rue Pasteur 95100 Argenteuil (95018_4060_c687b4 | str_distance: 0.4857/1.0, importance: 0.0298/0.1)
76BIS Avenue Pasteur 93100 Montreuil (93048_7160_017471 | str_distance: 0.3846/1.0, importance: 0.023/0.1)
76BIS Avenue Pasteur 93260 Les Lilas (93045_7130_0087d4 | str_distance: 0.3846/1.0, importance: 0.0199/0.1)
76BIS Rue Pasteur 02390 Origny-Sainte-Benoite (02575_0105_938436 | str_distance: 0.4/1.0, importance: 0.0032/0.1)
76BIS Rue Pasteur 41310 Saint-Amand-Longpré (41199_0074_75ff03 | str_distance: 0.3864/1.0, importance: 0.016/0.1)
76BIS Avenue Pasteur 66130 Ille-sur-Têt (66088_0308_9174b5 | str_distance: 0.3571/1.0, importance: 0.0058/0.1)
10.3 ms / 10 results
```

C'est un bug :)
Mais je suis pas sûr de comment le corriger proprement.
J'essaie de t'expliquer rapidement: lorsque le mode `autocomplete` est activé, le calcule de distance de chaîne donne un résultat de 1 si la chaîne *commence exactement* par la chaîne recherchée. Or, en l'occurrence, on a "76BIS" en base, et non pas "76 BIS", donc le résultat attendu n'est pas boosté comme il devrait.
Idéalement, c'est plutôt du côté des données qu'il faut corriger ça, je vais en causer à l'ami @cquest :)

**Comment by julien2512** [comment]
D'autant que les données BAN fournies sur le site font état de 2 colonnes différentes (numéro et répétition) !

**Comment by cquest** [comment]
La gestion des extensions de numéro n'est pas simple. Si on garde "76 BIS" et que l'on saisit "76bis" ça ne passe pas et inversement.
Il va sûrement falloir gérer ça de façon plus intelligente, par exemple en retraitant le chaine saisie pour toujours comparer sur "76BIS".
Autre possibilité, garder les 2 versions dans l'index...

**Comment by julien2512** [comment]
Je ne connaît pas de cas de figure où il y a un intérêt à garder les lettres et les chiffres accolés (contre-exemple ?). Je vous conseille de conserver "76 BIS" dans la base, et d'ajouter un prétraitement pour séparer nombres et lettre durant la recherche avant (ou durant) tokenization (cela ne coûte rien).

**Comment by yohanboniface** [comment]
> Je ne connaît pas de cas de figure où il y a un intérêt à garder les lettres et les chiffres accolés 
> (contre-exemple ?)

C'est une astuce un peu (trop) sioux pour que "76 BIS" ne matche pas les numéros de l'"Impasse du Pain Bis 07220 Viviers" ou "Passage des Chevreuils, SAINT BIS 69210 Bully" ou whatever. Je suis loin d'en être fier, mais en l'état je vois pas trop comment gérer ça plus proprement :/

Dans tous les cas faut qu'on corrige le point que tu nous as signalé si on garde cette feinte.

**Comment by yohanboniface** [comment]
(Il faut que je réimporte pour que ce soit visible sur l'API.)

**Comment by yohanboniface** [comment]
Bonne nouvelle: c'est réimporté!
Mauvaise nouvelle:  on en a profité pour mettre le nouveau jeu de données de la BAN, et le "76 bis" s'est transformé en "76 B".
Je sais pas si niveau données c'est une amélioration ou pas (tu connais le terrain par hasard?), mais du coup on se retrouve avec la même blague, voire pire, vu que ton "76 bis" est encore plus loin de "76 B" :/

**Comment by julien2512** [comment]
La version que j'avais utilisé comportait dans la BAN : 76, 76 A (*2), 76 B, 76 T, 76 BIS rue pasteur SAINT DENIS EN BUGEY.
Je télécharge une nouvelle version pour vérifier...

**Comment by julien2512** [comment]
Je confirme, 76 BIS est bien toujours présent dans la version actuellement sur le site (à moins que vous nous cachiez les mises à jour lol ; )) !
