### ISSUE TITLE
Ajout d'une colonne retournée "code INSEE" dans le géocodeur CSV

### ISSUE THREAD

**Issue by odtvince** [etalab/addok#66]
Un utilisateur du géocodeur CSV me fait part de la suggestion d'évolution suivante : ajouter une colonne avec le code INSEE de la commune (en plus de l'adresse rectifiée) dans le CSV retourné par le géocodeur CSV.
C'est peut-être un peu franco-français comme problématique, mais je peux voir de nombreux cas d'utilisation coté data sciences, donc je transmets.

**Comment by yohanboniface** [comment]
Oui, c'est une requête récurrente, franc-française comme tu dis, mais Addok, bon prince, nous laisse choisir les colonnes que l'on veut instance par instance, donc allons-y ;)

**Comment by yohanboniface** [comment]
Voilà, c'est en prod :)
