### ISSUE TITLE
Pour un point d'adresse, retourner l'id BAN !

### ISSUE THREAD

**Issue by parville** [etalab/addok#68]
Bonjour,

On dirait bien que l'id d'un point d'adresse ressemble à l'id d'une voie ....
Est-il possible de récupérer l'id BAN ? Et en cas de doublon dans la BAN - si si -, un seul suffira (le plus petit ?)

Merci

HP

**Comment by yohanboniface** [comment]
Euh, t'es sûr que c'est pas l'ID BAN?
@cquest *aiuto* :)

**Comment by parville** [comment]
Bah j'en mettrai mes cheveux longs à couper ! 

Id BAN de la forme ADRNIVX_0000000312893407 

addok renvoie un id de la forme : "76540_7125_5de4d9"  

_Amitiés_

**Comment by parville** [comment]
oups pour le close

**Comment by parville** [comment]
mince

**Comment by parville** [comment]
l'émotion ! J'ai cru voir un falcon passer !

**Comment by yohanboniface** [comment]
Dis donc, fais gaffe, j'ai cru que t'avais une attaque, j'ai failli appeler le SAMU

**Comment by parville** [comment]
:laughing:
J'attends que l'id soit correct pour faire une attaque 
 :angel:

**Comment by yohanboniface** [comment]
On doit réimporter pour que ce soit pris en compte.
