### ISSUE TITLE
Read bash import from stdin

### ISSUE THREAD

**Issue by frodrigo** [etalab/addok#74]
Allow import from stdin through pipe. So we can do :+1: 

```
$ bzcat BAN_odbl_33.json.bz2 | addok batch --
```

**Comment by yohanboniface** [comment]
This syntax works:

    (addok) edoardo:~/C/p/addok (master $=) addok batch < ~/Data/geo/ban/communes-context.json

I need to investigate why yours don't.

**Comment by yohanboniface** [comment]
Humm, this one works too:

    (addok) edoardo:~/C/p/addok (master $=) less ~/Data/geo/ban/communes-context.json | addok batch

Why adding '--' ?

**Comment by frodrigo** [comment]
Was a fictive command line. I never try. It's not in the doc !
