### ISSUE TITLE
GEODISTANCE 772210180J 48.1234 2.9876

### ISSUE THREAD

**Issue by frodrigo** [etalab/addok#75]
Runing in shell, quoted from doc:
```
GEODISTANCE 772210180J 48.1234 2.9876
```

Give an error:
```
Traceback (most recent call last):
  File "/home/fred/.virtualenvs/addok/bin/addok", line 9, in <module>
    load_entry_point('addok==0.2.0', 'console_scripts', 'addok')()
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/bin/__init__.py", line 50, in main
    cli()
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/debug.py", line 450, in __call__
    self.handle_command(command)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/debug.py", line 440, in handle_command
    return getattr(self, fx_name)(arg)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/debug.py", line 329, in do_geodistance
    km = haversine_distance((float(result.lat), float(result.lon)), center)
AttributeError: 'SearchResult' object has no attribute 'lat'
```

**Comment by yohanboniface** [comment]
Can you check that your document have lat and lon fields? `GET 772210180J`

**Comment by frodrigo** [comment]
I try it on a classic BAN full database. In lat and lon in original json data.

**Comment by frodrigo** [comment]
GET 772210180J return nothing

**Comment by yohanboniface** [comment]
weird, are you sure you don't have a space before "GET"?

**Comment by frodrigo** [comment]
" GET 772210180J" (with space) return content but no  "GET 772210180J"

**Comment by yohanboniface** [comment]
It should return the details of a document. "772210180J" is an existing document id, right?

**Comment by frodrigo** [comment]
No idea if it's existing. I copy the id from the doc.

**Comment by yohanboniface** [comment]
Aaaaaahh, ok :)
So, you need an existing id for this to give any result. I'll add a message when id doesn't exist.
When you issue a search, you have the result in the parenthesis:
```
> rue des lilas
Rue des Lilas 62000 Arras (62041_2410_e80166 | 0.9311818181818181)
```
The id of document "Rue des Lilas" is `62041_2410_e80166` for example.
