### ISSUE TITLE
Questions about filters

### ISSUE THREAD

**Issue by frodrigo** [etalab/addok#80]
Filters are for exact match only ? So:
- case sensitive
- no fuzzy matching

Can you explain why this query have results (have a filter on city):
/search?city=mmmmmm&q=rue

**Comment by yohanboniface** [comment]
Here is why:
```
> TOKENIZE mmmmmmmm
m
```

;)

**Comment by frodrigo** [comment]
I'm still not understand filters. Since there are tokonized, why there are case sensitive?
```
/search?city=paris&q=rue des lilas
```
Give no result, but
```
/search?city=Paris&q=rue des lilas
```
give results (note the capital).

**Comment by frodrigo** [comment]
I setup an filter on "city", but the result depend on case of query
```
/search?city=Paris&q=rue%20des%20lilas
```
return results. But (note "p" in lower)
```
/search?city=paris&q=rue%20des%20lilas
```
return no result.

This one return result, 
```
/search?city=m&q=rue
```
I'm almost sure I have no city named "m". And more over, results containts cities that haven't "m" in names.
