### ISSUE TITLE
Id pour une réponse de niveau Street

### ISSUE THREAD

**Issue by parville** [etalab/addok#83]
Bonjour, 

A quoi se raccroche l'id retourné pour un détrompage/reconnaissance de niveau street ?

Ex : http://api-adresse.data.gouv.fr/search/?q=rue%20jeanne%20d%27arc&citycode=76540
 
qui retourne  **id**: **_76540_4460_ac1ac8_**

Merci !

> {"features": [{"type": "Feature", "geometry": {"type": "Point", "coordinates": [1.091569, 49.443756]}, "properties": {"type": "street", "score": 0.9456454545454546, "label": "Rue Jeanne d'Arc 76000 Rouen", "postcode": "76000", "city": "Rouen", "id": "76540_4460_ac1ac8", "citycode": "76540", "name": "Rue Jeanne d'Arc", "context": "76, Seine-Maritime, Haute-Normandie"}}], "licence": "ODbL 1.0", "type": "FeatureCollection", "version": "draft", "query": "rue jeanne d'arc", "attribution": "BAN"}

**Comment by cquest** [comment]
Cet identifiant est composé su code INSEE de la commune, puis du code FANTOIR de la voie et/ou du lieu dit, suivit d'un hash (qui sert à l'unicité quand on a des codes postaux différents).
Cet identifiiant n'est pas calculé par addok, il est généré lors des traitements effectués par OSM-FR sur la diffusion ODbL.
