### ISSUE TITLE
Un caractère vous manque et la réponse est dépeuplée !

### ISSUE THREAD

**Issue by parville** [etalab/addok#85]
Pourquoi ce comportement  cas d'une __Recherche sur code insee contraint__

http://api-adresse.data.gouv.fr/search/?q=11%20RUE%20ma&citycode=59350&limit=20

:boom: **1 seule proposition**

http://api-adresse.data.gouv.fr/search/?q=11%20RUE%20mar&citycode=59350&limit=20

**autant de propositions que la limite demandée**

:+1: 

Merci :pray:

**Comment by yohanboniface** [comment]
L'autocomplétion est actuellement réglée pour commencer seulement à trois caractères. Essentiellement pour des histoires de performances et taille de l'index. Idéalement on voudrait passer à deux, mais ça demande pas mal d'optimisations, donc à voir dans le futur.
