### ISSUE TITLE
lng VS lon

### ISSUE THREAD

**Issue by frodrigo** [etalab/addok#88]
In english is more lng than lon. No other geocoding API use lon.

**Comment by yohanboniface** [comment]
> No other geocoding API use lon.
At least Photon and Pelias use `lon`. Assertions are better served by accurate arguments than hyperboles ;)
Certainly we can support both in the HTTP API anyway.

**Comment by yohanboniface** [comment]
Reopening, as I need to implement support of both `lon` and `lng`. :)

**Comment by frodrigo** [comment]
lng: opencagedata, google
longitude: HERE
lon: nominatime
