### ISSUE TITLE
reverse / type=commune ne fonctionne pas

### ISSUE THREAD

**Issue by parville** [etalab/addok#95]
Bonsoir,

l'exemple fournit dans la page ad hoc :black_joker:  ne fonctionne pas.

Pas plus celui-ci 

http://api-adresse.data.gouv.fr/reverse/?lon=0.23666&lat=49.537798&type=commune

Cordialement,

**Comment by yohanboniface** [comment]
Humm, on a deux soucis ici:

- le type "commune" n'existe pas, c'est `city` qu'il faut utiliser
- mais surtout addok ne fait pas d'extrapolation géographique, i.e. il n'est pas capable de savoir si un point fait partie du polygon de la géométrie d'une commune; tout ce qu'il fait c'est chercher des ponctuels dans un périmètre autour du point donné en entrée; s'il y a un filtre, il ne cherche que des points correspondant à ce filtre, et s'il y en a pas il renvoie rien.

Si ton besoin c'est de savoir dans quelle commune est un point en particulier, n'ajoute pas de filtre sur le type, plutôt regarde la clé `city` du résultat retourné.

Donc, si on reprends ton exemple, l'appel http://api-adresse.data.gouv.fr/reverse/?lon=0.23666&lat=49.537798 renvoie

```
{
  "features": [
    {
      "geometry": {
        "coordinates": [
          0.23666,
          49.537798
        ],
        "type": "Point"
      },
      "type": "Feature",
      "properties": {
        "city": "Saint-Martin-du-Manoir",
        "label": "33 Rue Montaigne 76290 Saint-Martin-du-Manoir",
        "housenumber": "33",
        "id": "76616_0140_1eb17c",
        "postcode": "76290",
        "name": "33 Rue Montaigne",
        "citycode": "76616",
        "context": "76, Seine-Maritime, Haute-Normandie",
        "score": 1.0,
        "type": "housenumber",
        "distance": 0
      }
    }
  ],
  "licence": "ODbL 1.0",
  "version": "draft",
  "type": "FeatureCollection",
  "attribution": "BAN"
}
```

Donc on est dans la commune de "Saint-Martin-du-Manoir".
